### ISSUE TITLE
Add description of origin of mikRopML to README

### ISSUE THREAD

**Issue by zenalapp** [SchlossLab/mikropml#102]

**Comment by BTopcuoglu** [comment]
Machine learning (ML) modeling of the human microbiome has the potential to identify microbial biomarkers and aid in the diagnosis of many diseases such as inflammatory bowel disease, diabetes, and colorectal cancer. Progress has been made toward developing ML models that predict health outcomes using microbiome features, but inconsistent adoption of training and evaluation methods call the validity of these models into question. Furthermore, there appears to be a preference by many researchers to favor increased model complexity over interpretability. To overcome these challenges, we generated a framework that provides a reproducible pipeline to train, evaluate, and interpret binary classification models and generate hypotheses to explain the underlying explanation of the model prediction. 

We published this [work](https://mbio.asm.org/content/11/3/e00434-20) in an American Society of Microbiology journal. However, we also wanted to make our ML pipeline available to a more general audience. Here we present mikRopML, an R package that train, evaluate, and interpret binary classification models with multiple ML algorithms.

**Comment by BTopcuoglu** [comment]
How is this @zenalapp and @kelly-sovacool?

**Comment by kelly-sovacool** [comment]
This looks great for the paper! But for the README I think we'll want something less formal, easier for a general audience to digest, and even more concise -- probably only a few sentences.

**Comment by zenalapp** [comment]
I agree with Kelly! Also it'd be fun if you could explain where the actual name of the package comes from :)
