### ISSUE TITLE
Refactor get_tuning_grid

### ISSUE THREAD

**Issue by kelly-sovacool** [SchlossLab/mikRopML#110]
Split into:
- [x] generate_tuning_grid
- [x] define_cv

Also:
- [ ] Don’t use conditionals, use named vector or list with quosure instead?

**Comment by BTopcuoglu** [comment]
Opened a branch for this: issue-110

**Comment by BTopcuoglu** [comment]
The current branch passes the devtools check. But we still need to refactor the code to remove conditionals. I'm not sure what would be the best way to do that, it will require many changes.

**Comment by kelly-sovacool** [comment]
@BTopcuoglu I'll take a look at it

**Comment by BTopcuoglu** [comment]
> @BTopcuoglu I'll take a look at it

I really like the change you made - using caret methods as the names

**Comment by kelly-sovacool** [comment]
@BTopcuoglu 
> I really like the change you made - using caret methods as the names

Thanks! I figured we might as well eliminate an extra step. The if-else block looks much better to me now this way.

I think a more urgent thing we could change is the way hyperparameters are given/defined. Can you think of a more user-friendly way to do it that wouldn't require filtering & splitting? Since users will likely just supply hyperparameters for one model/method if they don't use the defaults.
