### ISSUE TITLE
Refactor get_feature_importance

### ISSUE THREAD

**Issue by kelly-sovacool** [SchlossLab/mikRopML#112]
- [x] Change name from permutation_importance to get_feature_importance
~- [ ] Input: dataframe of features, correlation threshold~
- [x] Remove time
~- [ ] Maybe functionize group_correlated_features and find_permuted_aucs more~
- [x] Try to make it faster. Option to parallelize. E.g. future_apply functions. Future_apply would be a suggested package that’s not required unless the user wants to parallelize.

**Comment by zenalapp** [comment]
- [ ] Change name from permutation_importance to get_feature_importance
- [ ] Input: dataframe of features, correlation threshold
- [ ] Remove time
- [ ] Maybe functionize group_correlated_features and find_permuted_aucs more
- [ ] Try to make it faster. Option to parallelize. E.g. future_apply functions. Future_apply would be a suggested package that’s not required unless the user wants to parallelize.
