### ISSUE TITLE
Create a better way to specify the hyperparameters

### ISSUE THREAD

**Issue by BTopcuoglu** [SchlossLab/mikRopML#123]
Currently the user either uses a default dataframe we provide with hp and values for all the methods, or they make their own that is in the same structure. We need to come up with a better way. 

Maybe we can force usage of certain core hyperparameters and their corresponding values and the user can only expand on it?

**Comment by kelly-sovacool** [comment]
Ideas:
- Throw warning (not error) if method=regLogistic but hyperparameters aren't cost=L2_primal and epsilon=0.01.
