### ISSUE TITLE
Implement function to run multiple ML runs (different train/test splits) entirely in R

### ISSUE THREAD

**Issue by zenalapp** [SchlossLab/mikropml#165]
Idea for how to do this from Pat: use `map_???` and the `purrr` package to parallelize.

**Comment by kelly-sovacool** [comment]
actually would probably want to use the `furrr` package for parallelization

**Comment by kelly-sovacool** [comment]
This function should have the `ncores` argument instead of the `run_ml` function.

**Comment by kelly-sovacool** [comment]
Let's just use a `future.apply` function instead of `purrr`/`furrr` so we don't have to add another dependency.

**Comment by kelly-sovacool** [comment]
Another idea by @zenalapp: don't include this as a function, just show an example in the vignette.
