### ISSUE TITLE
Provide option for users to define train/test split and CV splits

### ISSUE THREAD

**Issue by zenalapp** [SchlossLab/mikropml#182]
This provides more flexibility, e.g. if users want to do leave-one-out cross-validation, or split into certain groups.

**Comment by kelly-sovacool** [comment]
I'm thinking about how best to implement this. Potential solutions:
1. An optional `train_indices` parameter to control which samples go into the train split, and an optional `cv_indices` parameter to control which of those samples end up in the cv training split (which would only make sense for `cv_times=1`).
2. An optional `group_partitions` parameter that defines which `groups` (required when this is used) are assigned to training, cv training, & testing sets. Could be a named list, e.g. `grouped_partitions = list(train = c('A', 'B'), cv_train = c('A'), test = c('C'))`. Then if a user wants to assign groups to certain splits but doesn't care how groups are selected for others, some could be `NULL`.

I think option 1 is more flexible, but option 2 is less work for the user. Maybe we could implement option 1, and write a helper function for users that have a use-case more like option 2.

**Comment by jdperera** [comment]
Are these options currently available? or any work around for now? I want to control which samples go into test split.
