### ISSUE TITLE
Make more functions back-end only

### ISSUE THREAD

**Issue by zenalapp** [SchlossLab/mikropml#195]
Kelly did this while writing functions, but Zena didn't. Probably good to go through them again anyways just to decide what to include as user-facing functions. We'll want to focus on making the documentation for those especially comprehensive.

**Comment by kelly-sovacool** [comment]
General rule of thumb: if the function is called by `run_ml()`, it should probably be user-facing in case users want to customize the pipeline (so include @export in the Roxygen doc). Otherwise, it can be internal (include @noRd in the Roxygen doc).
