### ISSUE TITLE
Add feature importance plot

### ISSUE THREAD

**Issue by zenalapp** [SchlossLab/mikropml#210]

**Comment by kelly-sovacool** [comment]
e.g. https://github.com/SchlossLab/mikropml/issues/122#issuecomment-706302650

**Comment by kelly-sovacool** [comment]
@zenalapp do you have example code for this from a paper?

**Comment by zenalapp** [comment]
It's from the very old pipeline, so the formatting is totally different and probably not helpful. I think it'd be easier to start from scratch.
