### ISSUE TITLE
Error: "long vectors not supported" with very large datasets

### ISSUE THREAD

**Issue by zenalapp** [SchlossLab/mikropml#218]
Error:

@kelly-sovacool do you have the error somewhere? 

We think this is because model.matrix doesn't like dataframes with a ton of features. One way you can try to get around this is by first filtering your features so that you only keep ones in, say, >5% of your samples.

**Comment by kelly-sovacool** [comment]
Error message thrown by `model.matrix`: `long vectors not supported`

This happens in both `preprocess_data()` and `run_ml()` with datasets with lots of columns (> 100,000).
