### ISSUE TITLE
Edit hyperparameter tuning vignette

### ISSUE THREAD

**Issue by NLesniak** [SchlossLab/mikropml#230]
- Add definition of hyperparameter to intro paragraph (lines 18-19)
- When describing alpha can range between param 0 and 1, unclear what the following "inclusive" means (line 74)
- It would be helpful to explicitly state how the model picks final hyperparameter value and use that to talk about how we know what is best for multiple splits (line 114)
- In SVM hyperparameters - could you more explain what sigma is, "defines how far the influence of a single training example reaches" is not clear? (line 208)
- In xgboost, hyperparameters are not defined (line 219) and confusing wording "need to be appropriate in relation"  (line 220)

**Comment by BTopcuoglu** [comment]
I'll edit to have one sentence explanations for each hyperparameter but then refer people to ML courses/papers for more detail like @kelly-sovacool suggested. Do you think that's reasonable @zenalapp?

**Comment by zenalapp** [comment]
Sounds good to me!

**Comment by BTopcuoglu** [comment]
I'm done with my edits. We can close this once merge #232
