### ISSUE TITLE
Correlation threshold parameter

### ISSUE THREAD

**Issue by kelly-sovacool** [SchlossLab/mikropml#263]
Currently, `preprocess_data()` collapses perfectly correlated features by default, but there isn't a way for users to relax that restriction (e.g. to just "strongly" correlated features) without creating their own preprocessing function. Maybe we should add a `corr_thresh` parameter so users can adjust this more easily? Or is this only supposed to be during feature importance after model training, in which case we already do have a `corr_thresh` parameter?

cc @zenalapp @courtneyarmour @pschloss

**Comment by zenalapp** [comment]
I think you want to include all features in `run_ml()` (except my understanding is you don't need to include exactly correlated features, hence the option to collapse perfectly correlated features in `preprocess_data()`). The correlation threshold is used after training the model for determining feature importance (you permute all correlated features together).
