### ISSUE TITLE
update get_corr_feats() to have correlation method option

### ISSUE THREAD

**Issue by courtneyarmour** [SchlossLab/mikropml#265]
add an option in get_corr_feats() (and other related functions) to choose the correlation method (options: pearson, spearman, kendall)

- [x] add option in get_corr_feats (default: spearman)
- [x] add option in group_correlated_features (default: spearman)
- [x] add option in find_feature_importance (default: spearman)
- [ ] update documentation
- [x] add new test with different method

Am I missing anything @kelly-sovacool ?

**Comment by kelly-sovacool** [comment]
Looks good @courtneyarmour!
