### ISSUE TITLE
Conversion of numeric outcomes to character error

### ISSUE THREAD

**Issue by ecmaggioncalda** [SchlossLab/mikropml#272]
When running the snakemake on a numeric outcome, the preprocessing step is converting numeric outcomes to character. Below is reproducible code using the otu_mini_bin data.

```
data_out <- preprocess_data(otu_mini_bin,
                            outcome_colname = "Otu00001")

str(data_out[[1]])

results_cont <- run_ml(data_out[[1]],
                       method = "glmnet",
                       seed = 42)
```

**Comment by kelly-sovacool** [comment]
FYI @ecmaggioncalda this bug fix was included in v1.1.0 which is now available on CRAN and conda!
