### ISSUE TITLE
classification of new (and outcome unknown) samples

### ISSUE THREAD

**Issue by fairquestion** [SchlossLab/mikropml#294]
Dear all,

I have succesfully trained a model and it is stored as a R object. Now I would like to classify samples whose outcome is unknown with this model. Do you have a straight forward way to do that?

I see that mikropml is useful to make a model out of a training list, get some top feature importance and some metrics... but once the model is stored as a R object... which are the command lines to use it as a classifier for unknown samples? after all we usually train models to implement them as classifiers for real world tasks, right?

Thanks,
Fair.

**Comment by kelly-sovacool** [comment]
Hi @fairquestion,

`run_ml()` returns the trained model object from `caret`, and you can use the `predict()` function (from R's `stats` package) to use the model to predict outcomes on new data.

``` r
library(dplyr)
library(mikropml)
results <- run_ml(otu_mini_bin,
                  'glmnet',
                  outcome_colname = 'dx',
                  seed = 2019)

# for the sake of example, let's simply use `test_data` and remove the outcome column
new_data <- results$test_data %>% select(-dx)
predictions <- predict(results$trained_model, new_data, type = 'prob')
head(predictions)
#>      cancer    normal
#> 1 0.4705888 0.5294112
#> 2 0.4886979 0.5113021
#> 3 0.5130865 0.4869135
#> 4 0.5291845 0.4708155
#> 5 0.5013173 0.4986827
#> 6 0.5000077 0.4999923

# note that the new data will need to have the same features (columns) as the
# training data, otherwise you will get an error
predictions <- predict(results$trained_model, new_data %>% select(-Otu00009), type = 'prob')
#> Error in eval(predvars, data, env): object 'Otu00009' not found
```

<sup>Created on 2022-03-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
