### ISSUE TITLE
use which run_ml() output to plot ROC curve?

### ISSUE THREAD

**Issue by zhq90** [SchlossLab/mikropml#296]
Would you explain the output of the run_ml() function?
Which data should be use to plot ROC curve?

I used ROCit to plot ROC curve, is this correct?

```r
library(mikropml)
library(ROCit)
rf_result <- run_ml(dataset = dfm,
                    method = "rf",
                    cv_times = 100,
                    kfold = 5,
                    outcome_colname = "Fgroup",
                    find_feature_importance = TRUE)
rf_obj <- rocit(score = rf_result$trained_model$pred$PD, class = rf_result$trained_model$pred$obs)
```

**Comment by kelly-sovacool** [comment]
@zhq90 We're not familiar with the ROCit package or with your particular dataset, but that does appear to be correct assuming that "PD" is a value in your outcome column. We plan to add example code for plotting AUROC curves in the future! #262

**Comment by kelly-sovacool** [comment]
We now have examples for plotting ROC & PRC curves here: http://www.schlosslab.org/mikropml/articles/parallel.html#roc-and-prc-curves
