### ISSUE TITLE
NaN as character causes some problems

### ISSUE THREAD

**Issue by sskoldas** [SchlossLab/mikropml#313]
When running mikropml through any model, it might change depending on the dataset, _positive predictive value_, _negative predictive value_ and _F1_ score might come as `NaN` which is assigned as a character. When combining each outcome of the model iteration to get performance in a tibble, `dplyr::bind_rows()` shows an error that **double** and **character** can't be combined.

Error backtrace is attached, below.

![crop](https://user-images.githubusercontent.com/55446435/200670071-85067090-9880-49b6-b9b7-da77ad7118f0.png)

**Comment by kelly-sovacool** [comment]
Hi @sskoldas, can you explain a bit more about how you're getting this error? I see it looks like you're calling mikropml with a Makefile. Can you share the R code that got you here?

`NaN` values are numerics (verified by running `class(NaN)`), therefore they can be combined with doubles by `dplyr::bind_rows()`. Maybe there are actually `NA_character_` values in your performance tibbles? Or are there literally characters like `"NaN"` that need to be changed to `NaN` with a `mutate()` & `if_else()`?

**Comment by sskoldas** [comment]
I think, there are characters like "NaN" because the error is gone when I run this:
 `iterative_run_ml_results %>% lapply(pluck, "performance")
map_dfr(performance, ~mutate(.x, across(where(is.character),as.logical))) %>%
  write_tsv(glue("{root}_performance.tsv"))`.

**Comment by kelly-sovacool** [comment]
Is your dataset very small and/or have highly imbalanced outcomes? In those cases the performance may be so bad that it can't be calculated. (Related to https://github.com/SchlossLab/mikropml/discussions/311)
