### ISSUE TITLE
Preprocessing in run_ml?

### ISSUE THREAD

**Issue by pschloss** [SchlossLab/mikropml#343]
When running one of the vignette `run_ml` pipelines we get the following output...

```
> run_ml(otu_small, "rf",
+   outcome_colname = "dx",
+   find_feature_importance = TRUE
+ )
Using 'dx' as the outcome column.
Training the model...
Training complete.
Finding feature importance...
Feature importance complete.
$trained_model
Random Forest 

161 samples
 60 predictor
  2 classes: 'cancer', 'normal' 

No pre-processing
```

Regardless of whether we give `run_ml` output from running `preprocess_data()` we get the "No pre-processing" statement as part of the `trained_model` object within the list...

```
otu_mini_bin_preproc <- preprocess_data(otu_mini_bin, 
                                       outcome_colname = "dx")
otu_mini_bin_preproc_ml<- run_ml(otu_mini_bin_preproc$dat_transformed, 
                       "glmnet", outcome_colname = "dx")
> otu_mini_bin_preproc_ml$trained_model
glmnet 

161 samples
 10 predictor
  2 classes: 'cancer', 'normal' 

No pre-processing
Resampling: Cross-Validated (5 fold, repeated 100 times) 
Summary of sample sizes: 129, 129, 129, 128, 129, 130, ... 
Resampling results across tuning parameters:
```

Is the "No pre-processing" flag a vestige of something `run_ml` did once upon a time or is there a way to do preprocessing within `run_ml`?

Pat

**Comment by kelly-sovacool** [comment]
Hey Pat, I believe that is a message from caret -- we run caret without preprocessing options since we have our own `preprocess_data()`. I'm not sure whether we can remove that message since it comes from caret.
