### ISSUE TITLE
Make this an R package

### ISSUE THREAD

**Issue by kelly-sovacool** [SchlossLab/mikRopML#46]
Reasons:
- Install the package with `devtools::install_github()`.
- Use `testthat` with continuous integration for automated testing.
- Generate documentation with `roxygen2` & `pkgdown`.

Required steps:

- [x] `roxygen2` comments (#58)
    - currently I inserted comment skeletons, but the actual documentation needs to be written before #58 is resolved.
- [x] `pkg::fcn()` syntax (#62) 
- [x] fix modified `caret` models (#74)
    - Begüm removed the custom models for now.
- [x] pass `devtools::check()`

**Comment by kelly-sovacool** [comment]
What should we name the package? It can only contain alphanumeric characters & periods ([naming guidelines here](http://r-pkgs.had.co.nz/package.html)).

This is step 1 before I can do anything else in setting up the package.

@pschloss @BTopcuoglu

**Comment by BTopcuoglu** [comment]
microML?

**Comment by kelly-sovacool** [comment]
On the Turkish theme, mikrop is microbe right? (used Google Translate)
Ideas on that theme:
- mikRop
- mikRopML

**Comment by BTopcuoglu** [comment]
Yeah! I like that too!

**Comment by BTopcuoglu** [comment]
@pschloss, we are moving on with the name "mikRopML" if you don't have any objections.

**Comment by pschloss** [comment]
Love it!

**Comment by kelly-sovacool** [comment]
Pronunciation from @BTopcuoglu: `meek-rope-M-L`

**Comment by pschloss** [comment]
you need to change the name of the repo, @BTopcuoglu

**Comment by kelly-sovacool** [comment]
Will have to get everyone to run `git remote set-url https://github.com/SchlossLab/mikRopML` after  we change the name of the repo.

**Comment by kelly-sovacool** [comment]
@BTopcuoglu will also need:
```
Title: What the Package Does (One Line, Title Case)
Description: What the package does (one paragraph).
```

**Comment by kelly-sovacool** [comment]
Waiting on #58 & #62 to be resolved

**Comment by BTopcuoglu** [comment]
@kelly-sovacool I'm resolving the bugs before I merge any PRs. I'll let you know when it's ready.

**Comment by BTopcuoglu** [comment]
I recommend changing the name from mikropML to something that is more general? What do you guys think @zenalapp and @kelly-sovacool?

**Comment by kelly-sovacool** [comment]
@BTopcuoglu I still like the name! I think it reflects where the project started without necessarily pigeon-holing the package for a specific use case, and its unique. If we were to change it to something that better encapsulates its broad applications, we would want to avoid making it sound too generic or forgettable.
