### ISSUE TITLE
All inputs and outputs should be R objects

### ISSUE THREAD

**Issue by zenalapp** [SchlossLab/mikRopML#96]
- [x] Remove hard-coded file paths from code
- [x] The user should provide e.g. a dataframe or other object in a specific format, not a file path. The user is responsible for reading the file or otherwise creating the object, not the package.
    - [x] Outcome vector
    - [x] Feature dataframe
    - [x] Hyperparameter dataframe (optional)
    - [x] Correlation matrix (or make this for them based on certain parameters?)
-  [x] Functions should return objects; not write files.

**Comment by kelly-sovacool** [comment]
This has been resolved over the course of #114
